name: Scheduled Sync Fork

on:
  schedule:
    # 每天北京时间清晨 6 点自动运行一次 (UTC 22:00)
    - cron: '0 22 * * *'
  workflow_dispatch: # 允许你在网页上手动点击触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_repository: byJoey/cfnewup
          upstream_branch: main
          target_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
